### ISSUE TITLE
Hard crash when 503 Service Unavailable

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo#59]
When Sumo is unavailable, uploader stops hard. Should rather wait a few seconds then try again.

Stack from example:
```
Traceback (most recent call last):
  File "<redacted>/root/bin/sumo_upload", line 8, in <module>
    sys.exit(main())
  File "<redacted>/root/lib/python3.6/site-packages/fmu/sumo/uploader/scripts/fm_fmu_uploader.py", line 33, in main
    case_metadata_path=case_metadata_path, sumo_connection=sumo_connection
  File "<redacted>/root/lib/python3.6/site-packages/fmu/sumo/uploader/_caseondisk.py", line 79, in __init__
    self._sumo_parent_id = self._get_sumo_parent_id()
  File "<redacted>/root/lib/python3.6/site-packages/fmu/sumo/uploader/_caseondisk.py", line 127, in _get_sumo_parent_id
    search_results = self.sumo_connection.api.searchroot(query, search_size=2)
  File "<redacted>/root/lib/python3.6/site-packages/fmu/sumo/uploader/_connection.py", line 32, in api
    name = self._api.userdata().get("name")
  File "<redacted>/root/lib/python3.6/site-packages/sumo/wrapper/_call_sumo_api.py", line 34, in userdata
    return self.callAzureApi.get_json(url, bearer)
  File "<redacted>/root/lib/python3.6/site-packages/sumo/wrapper/_call_azure_api.py", line 106, in get_json
    _raise_request_error_exception(response.status_code, response.text)
  File "<redacted>/root/lib/python3.6/site-packages/sumo/wrapper/_call_azure_api.py", line 12, in _raise_request_error_exception
    raise TransientError(code, message)
sumo.wrapper._request_error.TransientError: Transient Error with status code 503 and text <html><head><title>503 Service Unavailable</title></head><body><h1>Service Unavailable</h1></body></html>.
```

**Comment by perolavsvendsen** [comment]
As a temporary solution to ensure FMU workflows continue when something fails in the uploader, suggest to implement a catch-all.
